import { PromptBlock, PromptPreset } from '../types';

export const DEFAULT_BLOCKS: PromptBlock[] = [
  // --- PERSONA ---
  {
    id: 'block-persona-senior-architect',
    title: 'Senior Software Architect',
    category: 'persona',
    description: 'Act as a principal software engineer with 15+ years experience in distributed systems and clean architecture.',
    content: 'You are a Principal Software Architect with over 15 years of industry experience in {{technology_stack |* React 19, TypeScript, Node.js, Python, PostgreSQL, Docker}}. You value maintainability, low latency, idempotent design, clear separation of concerns, and pragmatic trade-offs.',
    tags: ['coding', 'architecture', 'expert'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'block-persona-creative-copywriter',
    title: 'High-Converting Copywriter',
    category: 'persona',
    description: 'Direct response copywriter trained on Ogilvy, Schwartz, and modern SaaS growth marketing.',
    content: 'You are an elite Direct-Response Copywriter specializing in {{niche | B2B SaaS & Năng suất, E-commerce & Bán lẻ, Fintech & Tài chính, AI & Tự động hoá}}. Your copy is punchy, emotionally resonant, psychologically persuasive, and free of corporate fluff. You hook attention in the first sentence.',
    tags: ['marketing', 'copywriting', 'growth'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'block-persona-data-scientist',
    title: 'Lead AI & Data Scientist',
    category: 'persona',
    description: 'Rigorous researcher analyzing data, statistics, model metrics, and empirical findings.',
    content: 'You are a Senior Machine Learning Engineer and Data Scientist. You communicate through statistical rigor, highlighting p-values, variance, bias trade-offs, and practical deployment considerations for {{domain | NLP & LLMs, Computer Vision, Recommendation Systems, Fraud Detection}}.',
    tags: ['ai', 'data', 'analytics'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'block-persona-socratic-tutor',
    title: 'Socratic Academic Tutor',
    category: 'persona',
    description: 'Patient teacher breaking down complex subjects using first principles and guided questioning.',
    content: 'You are a world-class academic tutor and communicator. Break down complex concepts in {{subject | Cấu trúc dữ liệu & Thuật toán, Trí tuệ nhân tạo, Kinh tế học & Tài chính, Tâm lý học hành vi}} using first principles, intuitive real-world analogies, and progressive disclosure tailored for {{learner_level | Người mới bắt đầu, Trung cấp, Chuyên sâu}}.',
    tags: ['education', 'learning', 'teaching'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // --- CONTEXT ---
  {
    id: 'block-context-business-problem',
    title: 'Business & Project Context',
    category: 'context',
    description: 'Set the company stage, user problem, and core objectives.',
    content: '### Background Context:\nWe are building a {{product_type | Web SaaS B2B, Mobile App, Browser Extension, E-commerce Platform}} targeting {{target_audience |* Developers, Startup Founders, Marketers, Khách hàng cá nhân}} in the {{market_region | Toàn cầu (Global), Việt Nam & Đông Nam Á, Bắc Mỹ (US/Canada)}} market. The primary challenge our users face is: {{core_pain_point}}.\nOur strategic goal for this initiative is {{business_objective |* Tăng trưởng doanh thu 30%, Cắt giảm thời gian xử lý 50%, Nâng cao sự hài lòng khách hàng}}.',
    tags: ['business', 'strategy', 'context'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'block-context-codebase-env',
    title: 'Codebase & Tech Environment',
    category: 'context',
    description: 'Specify programming language, runtime version, framework, and dependencies.',
    content: '### Environment Specifications:\n- Language/Runtime: {{language_runtime | TypeScript 5.8 trên Node 22, Python 3.12, Go 1.23, Rust 1.80}}\n- Framework: {{framework | React & Vite, Next.js App Router, Vue 3 & Vite, FastAPI}}\n- Database/Storage: {{database | IndexedDB / Client Storage, PostgreSQL, SQLite, MongoDB}}\n- Design Constraints: Must run in modern browser environments without third-party tracking.',
    tags: ['dev', 'tech-stack', 'specs'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'block-context-brand-voice',
    title: 'Brand Identity & Guidelines',
    category: 'context',
    description: 'Establish brand tone, core values, and communication rules.',
    content: '### Brand Identity:\nOur brand {{brand_name}} stands for {{brand_pillars | Đổi mới sáng tạo & Đơn giản, Tin cậy & Bảo mật tối đa, Tốc độ vượt trội & Linh hoạt}}. We communicate with empathy, clarity, and authority. We avoid buzzwords like "revolutionize", "game-changer", and "delve".',
    tags: ['branding', 'tone', 'guidelines'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // --- INSTRUCTIONS ---
  {
    id: 'block-inst-step-by-step',
    title: 'Step-by-Step Chain-of-Thought',
    category: 'instructions',
    description: 'Enforce methodical reasoning and step-by-step breakdown before final answer.',
    content: '### Detailed Instructions:\n1. Deconstruct the request into core components.\n2. Consider edge cases, assumptions, and potential bottlenecks.\n3. Formulate the recommended solution step-by-step.\n4. Validate the solution against our requirements: {{specific_requirements}}.\n5. Present the final recommendation clearly.',
    tags: ['reasoning', 'methodology', 'cot'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'block-inst-code-refactor',
    title: 'Strict Code Refactoring & Audit',
    category: 'instructions',
    description: 'Perform security, performance, and readability audit on provided code.',
    content: '### Code Review & Refactoring Tasks:\n- Identify any O(N^2) complexity or memory leaks.\n- Check for security vulnerabilities (injection, XSS, insecure state mutations).\n- Refactor to clean, idiomatic TypeScript with strict typing.\n- Include concise inline comments explaining non-trivial logic.',
    tags: ['coding', 'refactor', 'security'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'block-inst-copy-variations',
    title: 'A/B Testing Angle Generator',
    category: 'instructions',
    description: 'Generate distinct marketing angles (Fear of missing out, Social proof, Direct benefit).',
    content: 'Generate {{variation_count | 3 góc tiếp cận, 5 góc tiếp cận, 7 góc tiếp cận}} distinct creative angles for {{campaign_goal}}:\n- Angle 1 (Direct Problem & Pain Relief)\n- Angle 2 (Curiosity & Contrarian Insight)\n- Angle 3 (Social Proof & Authority/Data Driven)\nFor each angle, write a compelling Headline, Subhead, and Call-to-Action (CTA).',
    tags: ['marketing', 'ab-testing', 'angles'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // --- CONSTRAINTS ---
  {
    id: 'block-const-hallucination-guard',
    title: 'Anti-Hallucination Guardrails',
    category: 'constraints',
    description: 'Forbid speculation, cite verifiable sources, admit unknowns immediately.',
    content: '### Strict Accuracy Constraints:\n- Do NOT speculate or invent facts, statistics, or URLs.\n- If a specific piece of information is unknown or ambiguous, state "I do not have sufficient data for this" clearly.\n- Base all conclusions exclusively on verifiable evidence or standard engineering consensus.',
    tags: ['accuracy', 'safety', 'guardrails'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'block-const-conciseness',
    title: 'Zero Fluff & Strict Brevity',
    category: 'constraints',
    description: 'Enforces dense, high-signal information density without conversational filler.',
    content: '### Conciseness Rules:\n- Skip greetings, pleasantries, apologies, and concluding boilerplate (e.g. "I hope this helps!").\n- Maximize signal-to-noise ratio: use bullet points and bold highlights.\n- Keep your entire response under {{max_word_limit | 150 từ, 250 từ, 500 từ, 1000 từ}} words.',
    tags: ['brevity', 'high-signal', 'direct'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'block-const-no-jargon',
    title: 'Plain English & Layman Simplicity',
    category: 'constraints',
    description: 'Prevent incomprehensible technical jargon; keep readability at grade 8 level.',
    content: '### Language Constraints:\n- Write at a grade-level 8 readability.\n- Explain all specialized terminology with everyday analogies.\n- Avoid Latin phrases or obscure academic idioms.',
    tags: ['simplicity', 'plain-english'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // --- STYLE ---
  {
    id: 'block-style-executive',
    title: 'Executive C-Level Tone',
    category: 'style',
    description: 'Crisp, strategic, ROI-focused tone designed for busy executives.',
    content: '### Tone & Style:\nAdopt an executive leadership voice: confident, objective, ROI-centric, and forward-looking. Focus on high-level impact, risk mitigation, and actionable next steps.',
    tags: ['executive', 'c-suite', 'tone'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'block-style-playful-tech',
    title: 'Engaging & Witty Tech Voice',
    category: 'style',
    description: 'Approachable, developer-friendly, slightly witty yet highly practical.',
    content: '### Tone & Style:\nFriendly, witty, and developer-native. Think Stripe documentation meets great Twitter tech essays. Use clean code blocks and insightful commentary.',
    tags: ['witty', 'developer', 'engaging'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'block-style-vietnamese-pro',
    title: 'Tiếng Việt Chuyên Nghiệp',
    category: 'style',
    description: 'Ngôn phong tiếng Việt tự nhiên, chính xác, lịch thiệp và chuẩn mực chuyên ngành.',
    content: '### Ngôn ngữ & Phong cách:\nTrình bày hoàn toàn bằng tiếng Việt chuẩn mực, mạch lạc, tự nhiên. Sử dụng thuật ngữ chuyên ngành công nghệ / kinh doanh chính xác (kèm tiếng Anh gốc trong ngoặc đơn khi cần thiết để tránh hiểu nhầm).',
    tags: ['vietnamese', 'language', 'pro'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // --- OUTPUT ---
  {
    id: 'block-output-json-schema',
    title: 'Strict JSON Schema Output',
    category: 'output',
    description: 'Returns only raw, valid JSON matching the specified schema without markdown wrappers.',
    content: '### Output Format Requirements:\nReturn ONLY a valid JSON object matching the following structure:\n```json\n{\n  "status": "success",\n  "data": {\n    "title": "string",\n    "summary": "string",\n    "keyPoints": ["string"],\n    "recommendedAction": "string"\n  }\n}\n```\nDo not include any conversational text before or after the JSON. Ensure valid escaping.',
    tags: ['json', 'structured', 'schema'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'block-output-markdown-table',
    title: 'Markdown Comparison Table',
    category: 'output',
    description: 'Organize trade-offs and options into clean GitHub-flavored markdown tables.',
    content: '### Output Format Requirements:\nFormat the comparison as a Markdown table with columns: [Option | Pros | Cons | Cost/Effort | Recommendation]. Follow the table with a 2-paragraph executive summary.',
    tags: ['markdown', 'table', 'comparison'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'block-output-actionable-checklist',
    title: 'Numbered Action Plan & Checklist',
    category: 'output',
    description: 'Action-oriented bulleted checklist with estimated completion time.',
    content: '### Output Format Requirements:\nStructure your deliverable as an execution checklist:\n- [ ] Phase 1: Immediate Wins (Day 1-3)\n- [ ] Phase 2: Core Implementation (Week 1-2)\n- [ ] Phase 3: Validation & Optimization (Week 3)\nInclude time estimates and verification criteria for each milestone.',
    tags: ['checklist', 'roadmap', 'action-plan'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // --- EXAMPLES ---
  {
    id: 'block-examples-fewshot',
    title: 'Few-Shot Quality Demonstration',
    category: 'examples',
    description: 'Provide an input/output quality standard for the AI to emulate.',
    content: '### Reference Example:\nInput: {{example_input}}\nOutput: {{example_output}}\nModel your tone, depth, and output formatting strictly after this reference quality standard.',
    tags: ['few-shot', 'examples', 'calibration'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

const getDefBlock = (id: string): PromptBlock => {
  const found = DEFAULT_BLOCKS.find((b) => b.id === id);
  if (!found) {
    throw new Error(`Default block with id "${id}" not found.`);
  }
  return found;
};

export const DEFAULT_PRESETS: PromptPreset[] = [
  {
    id: 'preset-saas-copywriter',
    name: 'SaaS High-Converting Hero Copy',
    description: 'Chains Direct-Response Copywriter, Business Context, A/B Testing Angles, and Brevity.',
    category: 'Marketing',
    canvasItems: [
      {
        instanceId: 'inst-1',
        blockId: 'block-persona-creative-copywriter',
        title: getDefBlock('block-persona-creative-copywriter').title,
        category: 'persona',
        content: getDefBlock('block-persona-creative-copywriter').content,
        prefix: '',
        suffix: '\n\n',
        isEnabled: true,
        order: 0,
      },
      {
        instanceId: 'inst-2',
        blockId: 'block-context-business-problem',
        title: getDefBlock('block-context-business-problem').title,
        category: 'context',
        content: getDefBlock('block-context-business-problem').content,
        prefix: '',
        suffix: '\n\n',
        isEnabled: true,
        order: 1,
      },
      {
        instanceId: 'inst-3',
        blockId: 'block-inst-copy-variations',
        title: getDefBlock('block-inst-copy-variations').title,
        category: 'instructions',
        content: getDefBlock('block-inst-copy-variations').content,
        prefix: '',
        suffix: '\n\n',
        isEnabled: true,
        order: 2,
      },
      {
        instanceId: 'inst-4',
        blockId: 'block-const-conciseness',
        title: getDefBlock('block-const-conciseness').title,
        category: 'constraints',
        content: getDefBlock('block-const-conciseness').content,
        prefix: '',
        suffix: '',
        isEnabled: true,
        order: 3,
      },
    ],
    variableValues: {
      niche: 'B2B SaaS & Năng suất',
      product_type: 'Web SaaS B2B',
      target_audience: 'Developers, Startup Founders',
      market_region: 'Toàn cầu (Global)',
      core_pain_point: 'Soạn thảo prompt lặp đi lặp lại và thiếu hệ thống lưu trữ có tổ chức',
      business_objective: 'Tăng trưởng doanh thu 30%, Cắt giảm thời gian xử lý 50%',
      variation_count: '3 góc tiếp cận',
      campaign_goal: 'Landing Page Hero Headline & Subhead',
      max_word_limit: '250 từ',
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'preset-senior-code-architect',
    name: 'Senior Code Audit & Architecture',
    category: 'Engineering',
    description: 'Deploys Principal Architect persona, Environment context, Refactoring rules, and Anti-Hallucination constraints.',
    canvasItems: [
      {
        instanceId: 'inst-arch-1',
        blockId: 'block-persona-senior-architect',
        title: getDefBlock('block-persona-senior-architect').title,
        category: 'persona',
        content: getDefBlock('block-persona-senior-architect').content,
        prefix: '',
        suffix: '\n\n',
        isEnabled: true,
        order: 0,
      },
      {
        instanceId: 'inst-arch-2',
        blockId: 'block-context-codebase-env',
        title: getDefBlock('block-context-codebase-env').title,
        category: 'context',
        content: getDefBlock('block-context-codebase-env').content,
        prefix: '',
        suffix: '\n\n',
        isEnabled: true,
        order: 1,
      },
      {
        instanceId: 'inst-arch-3',
        blockId: 'block-inst-code-refactor',
        title: getDefBlock('block-inst-code-refactor').title,
        category: 'instructions',
        content: getDefBlock('block-inst-code-refactor').content,
        prefix: '',
        suffix: '\n\n',
        isEnabled: true,
        order: 2,
      },
      {
        instanceId: 'inst-arch-4',
        blockId: 'block-const-hallucination-guard',
        title: getDefBlock('block-const-hallucination-guard').title,
        category: 'constraints',
        content: getDefBlock('block-const-hallucination-guard').content,
        prefix: '',
        suffix: '',
        isEnabled: true,
        order: 3,
      },
    ],
    variableValues: {
      technology_stack: 'React 19, TypeScript, PostgreSQL',
      language_runtime: 'TypeScript 5.8 trên Node 22',
      framework: 'React & Vite',
      database: 'IndexedDB / Client Storage',
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'preset-json-api-generator',
    name: 'Strict JSON Data Extraction',
    category: 'Data & AI',
    description: 'Chains AI Scientist persona, Step-by-Step reasoning, and Strict JSON Schema Output.',
    canvasItems: [
      {
        instanceId: 'inst-json-1',
        blockId: 'block-persona-data-scientist',
        title: getDefBlock('block-persona-data-scientist').title,
        category: 'persona',
        content: getDefBlock('block-persona-data-scientist').content,
        prefix: '',
        suffix: '\n\n',
        isEnabled: true,
        order: 0,
      },
      {
        instanceId: 'inst-json-2',
        blockId: 'block-inst-step-by-step',
        title: getDefBlock('block-inst-step-by-step').title,
        category: 'instructions',
        content: getDefBlock('block-inst-step-by-step').content,
        prefix: '',
        suffix: '\n\n',
        isEnabled: true,
        order: 1,
      },
      {
        instanceId: 'inst-json-3',
        blockId: 'block-output-json-schema',
        title: getDefBlock('block-output-json-schema').title,
        category: 'output',
        content: getDefBlock('block-output-json-schema').content,
        prefix: '',
        suffix: '',
        isEnabled: true,
        order: 2,
      },
    ],
    variableValues: {
      domain: 'NLP & LLMs',
      specific_requirements: 'Cấu trúc dữ liệu JSON thuần, không bọc markdown tag, đúng 4 trường schema đã định',
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'preset-socratic-vietnamese-mentor',
    name: 'Socratic Mentor & Tiếng Việt Chuyên Sâu',
    category: 'Education',
    description: 'Phương pháp đặt câu hỏi dẫn dắt Socratic, phân tích từ gốc rễ kết hợp văn phong tiếng Việt chuẩn mực và kế hoạch hành động.',
    canvasItems: [
      {
        instanceId: 'inst-soc-1',
        blockId: 'block-persona-socratic-tutor',
        title: getDefBlock('block-persona-socratic-tutor').title,
        category: 'persona',
        content: getDefBlock('block-persona-socratic-tutor').content,
        prefix: '',
        suffix: '\n\n',
        isEnabled: true,
        order: 0,
      },
      {
        instanceId: 'inst-soc-2',
        blockId: 'block-inst-step-by-step',
        title: getDefBlock('block-inst-step-by-step').title,
        category: 'instructions',
        content: getDefBlock('block-inst-step-by-step').content,
        prefix: '',
        suffix: '\n\n',
        isEnabled: true,
        order: 1,
      },
      {
        instanceId: 'inst-soc-3',
        blockId: 'block-style-vietnamese-pro',
        title: getDefBlock('block-style-vietnamese-pro').title,
        category: 'style',
        content: getDefBlock('block-style-vietnamese-pro').content,
        prefix: '',
        suffix: '\n\n',
        isEnabled: true,
        order: 2,
      },
      {
        instanceId: 'inst-soc-4',
        blockId: 'block-output-actionable-checklist',
        title: getDefBlock('block-output-actionable-checklist').title,
        category: 'output',
        content: getDefBlock('block-output-actionable-checklist').content,
        prefix: '',
        suffix: '',
        isEnabled: true,
        order: 3,
      },
    ],
    variableValues: {
      subject: 'Trí tuệ nhân tạo',
      learner_level: 'Người mới bắt đầu',
      specific_requirements: 'Giải thích trực quan bằng ví dụ đời sống thực tế, phân kỳ lộ trình 3 giai đoạn rõ ràng',
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'preset-brand-growth-pitch',
    name: 'Brand Identity & Comparison Pitch',
    category: 'Business',
    description: 'Thiết lập bản sắc thương hiệu, văn phong điều hành C-level và bảng so sánh đa chiều các giải pháp.',
    canvasItems: [
      {
        instanceId: 'inst-brand-1',
        blockId: 'block-context-brand-voice',
        title: getDefBlock('block-context-brand-voice').title,
        category: 'context',
        content: getDefBlock('block-context-brand-voice').content,
        prefix: '',
        suffix: '\n\n',
        isEnabled: true,
        order: 0,
      },
      {
        instanceId: 'inst-brand-2',
        blockId: 'block-style-executive',
        title: getDefBlock('block-style-executive').title,
        category: 'style',
        content: getDefBlock('block-style-executive').content,
        prefix: '',
        suffix: '\n\n',
        isEnabled: true,
        order: 1,
      },
      {
        instanceId: 'inst-brand-3',
        blockId: 'block-output-markdown-table',
        title: getDefBlock('block-output-markdown-table').title,
        category: 'output',
        content: getDefBlock('block-output-markdown-table').content,
        prefix: '',
        suffix: '',
        isEnabled: true,
        order: 2,
      },
    ],
    variableValues: {
      brand_name: 'PromptMixer',
      brand_pillars: 'Đổi mới sáng tạo & Đơn giản, Tốc độ vượt trội & Linh hoạt',
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
